name: Scrape connection puzzle json

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Do the thing:
      run: |-
        mkdir -p data
				curl https://www.nytimes.com/svc/connections/v1/$(date +%Y-%M-%d).json > data/$(date +%Y-%M-%d).json
				git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add data/*.json
        timestamp=$(date -u)
        git commit -m "Latest: ${timestamp}" || exit 0
        git pull --rebase
        git push
